### ISSUE TITLE
Fatal error: Invalid handle returned - for all connections if one fails

### ISSUE THREAD

**Issue by eziitiss** [Azure/msphpsql#116] opened 2016-07-28 20:18 UTC
After one connection using pdo_sqlsrv v4.0.8629.2 fails, for example because of incorrect user/pass, All the other connections also are failing with PHP Fatal error: Invalid handle returned.

Environment: Win10, Apache/2.4.23 (Win64) OpenSSL/1.0.2h PHP/7.0.9 using php_pdo_sqlsrv_7_ts_x64.dll.

Reproducing:
2 php scripts that are creating DB connections using php, like:
file1.php: 
`<?php
try{
	$dbconnection = new PDO('sqlsrv:Server=localhost;Database=cdr41', 'existinguser', 'existingpassword');
	echo 'OK';
}catch(PDOException $e){
	echo $e->getMessage();
}
?>`

file2.php:
 `<?php
try{
	$dbconnection = new PDO('sqlsrv:Server=localhost;Database=cdr41', 'fakeuser', 'fakepassword');
	echo 'OK';
}catch(PDOException $e){
	echo $e->getMessage();
}
?>`

I can run file1.php multiple times without any problems, but after running even once file2.php, first time file2.php generates and exception, like it should, but after that file1.php and file2.php are failing with Fatal error: Invalid handle returned.

When switching back to 32bit apache + php + pdo SQL driver 3.2 all works as expected.

**Comment by meet-bhagdev** [comment] 2016-07-29 23:43
@eziitiss We are looking into this. We will keep you posted.

**Comment by Yahasana** [comment] 2016-07-31 16:12
:-1: m2

**Comment by meet-bhagdev** [comment] 2016-08-01 08:40
@Yahasana we are actively investigating this. Do you have a repro script that you can share with us?

**Comment by eziitiss** [comment] 2016-08-01 11:57
@meet-bhagdev I have already posted my two test scripts. Nothing more is needed, just a local MSSQL server (in my case: v13.0.1708) with existing DB name "CDR41" and existing user "existinguser" with password "existingpassword" and not existing user "fakeuser". Sure - you can rename the DB and users how you like - just rename them also in PDO connection string :) .
What I did not mention in my original post - to recover from this failure I need to restart my Apache server. If you need some more info or some debug - let me know.

**Comment by mlhkr** [comment] 2016-08-01 13:28
Now I remember that nearly have the same issue but not about password.
Probably after getting php timeout while pdo query, the other instances starts to give the same error till I restart the IIS 8.5. A little bit busy here but try to reproduce the error too.

**Comment by super-vip** [comment] 2016-08-06 08:41
I have the same problem here. 
4.0.2 - Linux
4.1.0 -windows

**Comment by ethanhann-ensembleads** [comment] 2016-08-07 00:05
I get this error like every 10 connections. Turning connection pooling off seems to make the error go away.

**Comment by meet-bhagdev** [comment] 2016-08-08 20:06
@ethanhann-tr @super-vip @eziitiss @mlhkr We are looking into this and will aim to fix this asap. Stay tuned :)

**Comment by lancepioch** [comment] 2016-08-12 16:59
This same thing is happening to me.

I'm using:

* Ubuntu 16.04
* PHP 7.0.9
* Nginx 1.11.1
* Laravel 5.2.43
* msphpsql 4.0.2 - Linux

### **Important Note: It's happening exactly every 3 requests.**

**Comment by meet-bhagdev** [comment] 2016-08-12 17:22
@lancepioch @all We are able to repro this bug in our lab. We are fixing it as we talk and will aim to fix it in our next release. Our next release should be out very soon.

**Comment by david-garcia-garcia** [comment] 2016-08-12 18:33
Just for the record, someone also reported this on Drupal.org:

https://www.drupal.org/node/2772037

**Comment by meet-bhagdev** [comment] 2016-08-15 06:46
@all, we are actively fixing this bug. Can you provide a repro script similar to the one @eziitiss shared? We would like to test against it to validate our fix.

**Comment by ethan-tr** [comment] 2016-08-23 19:57
@meet-bhagdev I am seeing this issue while using Laravel, so I don't have a simple script I can extract and share. Were you able to validate your fix? Can we expect a release with it soon?

**Comment by rodrigopedra** [comment] 2016-08-24 01:17
@ethan-tr , in your config/database.php add `'pooling' => false,' to your database parameters, as follow:

~~~sql
'connections' => [
        'sqlsrv' => [
            'driver'   => 'sqlsrv',
            'host'     => env( 'DB_HOST' ),
            'port'     => env( 'DB_PORT', 1433 ),
            'database' => env( 'DB_DATABASE' ),
            'username' => env( 'DB_USERNAME' ),
            'password' => env( 'DB_PASSWORD' ),
            'prefix'   => '',
            'charset'  => 'UTF-8',
            'appname'  => 'App name',
            'pooling'  => false,
        ],
],
~~~

**Comment by david-garcia-garcia** [comment] 2016-08-24 09:07
@meet-bhagdev This issue is really annoying. If you already have a fix, please consider doing a release even if we have to wait longer for other fixes.

**Comment by meet-bhagdev** [comment] 2016-08-24 22:09
@david-garcia-garcia @rodrigopedra @lancepioch @eziitiss @Yahasana @super-vip @mlhkr : We just released our next preview: https://github.com/Azure/msphpsql/releases/tag/v4.0.3-Linux. We have attempted to fix this bug. Please help us validate. If there are more issues, update this thread and we will take a look at it.

**Comment by eziitiss** [comment] 2016-08-25 07:22
@meet-bhagdev: Any schedule on Windows version ?

**Comment by mlhkr** [comment] 2016-08-25 07:24
It's already released:
https://github.com/Azure/msphpsql/releases/tag/v4.1.1-Windows

**Comment by eziitiss** [comment] 2016-08-25 08:17
Can confirm issue solved in my case using 4.1.1.
Thank you!

**Comment by ethan-tr** [comment] 2016-08-25 19:33
The 4.0.3 driver seems to have fixed the issue in my tests.

**Comment by rodrigopedra** [comment] 2016-08-26 03:18
@meet-bhagdev changed our app today and it seems ok with the new version. thanks!

**Comment by meet-bhagdev** [comment] 2016-08-26 17:56
@rodrigopedra @ethan-tr @eziitiss Glad to hear the issue is fixed 👍 Going to close this issue. @All feel free to re-open the issue if you need to.

**Closed by meet-bhagdev** 2016-08-26 17:56 UTC

**Comment by ahmeti** [comment] 2017-08-04 23:37
I spent an hour. But when I removed the port number, it worked out.

```
'connections' => [
        'sqlsrv' => [
            'driver'   => 'sqlsrv',
            'host'     => env( 'DB_HOST' ),
            'port'     => '',
            'database' => env( 'DB_DATABASE' ),
            'username' => env( 'DB_USERNAME' ),
            'password' => env( 'DB_PASSWORD' ),
            'prefix'   => '',
            'charset'  => 'UTF-8',
            'pooling'  => false,
        ],
],
```
