### ISSUE TITLE
php_sqlsrv_7_nts_x64.dll - Large SQL-statements

### ISSUE THREAD

**Issue by ViewGEW** [Azure/msphpsql#111] opened 2016-07-14 13:21 UTC
PHP 7 SQL-server 2008R2
php_sqlsrv ver. 4.0.8629.3
This extension seems not to be able to execute large SQL-statements. The generated SQL-code works fine with the deprecated mssql.dll and when the code is ran directly on the SQL-server.
Execution reports no errors and everything looks OK until I check the result in db.

Test was done with script size approx. 4MB. Small scripts runs without any problems.
The testscript contained nearly 2000 INSERT-statements.

GEW

**Comment by meet-bhagdev** [comment] 2016-07-22 18:58
@ViewGEW happy to help you out here. For us to further debug this, we will need a repro script and a sample schema. Once we  Feel free to email me at meetb@microsoft.com.

**Comment by meet-bhagdev** [comment] 2016-08-11 00:02
@ViewGEW, we did some investigation on this. Seems like when executing a large batch of SQL statements, Microsoft SQL Server may stop processing the batch before all statements in the batch are executed. When processing the results of a batch, SQL Server fills the output buffer of the connection with the result sets that are created by the batch. These result sets must be processed by the client application. If you are executing a large batch with multiple result sets, SQL Server fills that output buffer until it hits an internal limit and cannot continue to process more result sets. At that point, control returns to the client. This behavior is by design.

Client app should flush all the pending result sets. As soon as all pending result sets are consumed by the client, SQL Server completes executing the batch. Client app can call sqlsrv_next_result() until it returns NULL. 

Here is a script for reference
```
<?php
//Initialization
$serverName = "";
$uid = "";
$pwd = "";
$database = "";
// Path to the create table script
$createTableScript = "pathToCreateTable/table.sql";
// Path to the script with a large batch of SQl statements
$largeBatchScript = "pathToInsertStmts/repro_script.sql";


$conn_array = array (
    "UID" => $uid,
    "PWD" => $pwd,
    "Database" => $database,
);

// Connect
$conn = sqlsrv_connect($serverName, $conn_array);
if( $conn === false ) 
{
    die( print_r( sqlsrv_errors(), true));
}

// Create table using $createTableScript
$tsql = file_get_contents($createTableScript);
$stmt = sqlsrv_query( $conn, $tsql);
if( $stmt === false )
{
    die( print_r( sqlsrv_errors(), true));
}

// Execute the script with a large batch of SQl statements
$tsql = file_get_contents($largeBatchScript);
$stmt = sqlsrv_query( $conn, $tsql);
if( $stmt === false ) 
{
    die( print_r( sqlsrv_errors(), true));
}

// When you execute a large batch of SQL statements ,
// Microsoft SQL Server may stop processing the batch before all statements in the batch are executed.
// https://support.microsoft.com/en-us/kb/827575
// Uncomment the next line to flush all the pending result sets. 

//while ( sqlsrv_next_result ( $stmt ) != NULL ){};

sqlsrv_free_stmt ( $stmt );
sqlsrv_close ( $conn );
?>
```

**Comment by ViewGEW** [comment] 2016-08-11 08:54
Hi!

Thanks! It worked!


//Geir Witsø

Fra: Meet Bhagdev [mailto:notifications@github.com]
Sendt: 11. august 2016 02:03
Til: Azure/msphpsql
Kopi: Geir Witsø - View Software; Mention
Emne: Re: [Azure/msphpsql] php_sqlsrv_7_nts_x64.dll - Large SQL-statements (#111)


@ViewGEW<https://github.com/ViewGEW>, we did some investigation on this. Seems like when executing a large batch of SQL statements, Microsoft SQL Server may stop processing the batch before all statements in the batch are executed. When processing the results of a batch, SQL Server fills the output buffer of the connection with the result sets that are created by the batch. These result sets must be processed by the client application. If you are executing a large batch with multiple result sets, SQL Server fills that output buffer until it hits an internal limit and cannot continue to process more result sets. At that point, control returns to the client. This behavior is by design.

Client app should flush all the pending result sets. As soon as all pending result sets are consumed by the client, SQL Server completes executing the batch. Client app can call sqlsrv_next_result() until it returns NULL.

Here is a script for reference

<?php

//Initialization

$serverName = "";

$uid = "";

$pwd = "";

$database = "";

// Path to the create table script

$createTableScript = "pathToCreateTable/table.sql";

// Path to the script with a large batch of SQl statements

$largeBatchScript = "pathToInsertStmts/repro_script.sql";





$conn_array = array (

    "UID" => $uid,

    "PWD" => $pwd,

    "Database" => $database,

);



// Connect

$conn = sqlsrv_connect($serverName, $conn_array);

if( $conn === false )

{

    die( print_r( sqlsrv_errors(), true));

}



// Create table using $createTableScript

$tsql = file_get_contents($createTableScript);

$stmt = sqlsrv_query( $conn, $tsql);

if( $stmt === false )

{

    die( print_r( sqlsrv_errors(), true));

}



// Execute the script with a large batch of SQl statements

$tsql = file_get_contents($largeBatchScript);

$stmt = sqlsrv_query( $conn, $tsql);

if( $stmt === false )

{

    die( print_r( sqlsrv_errors(), true));

}



// When you execute a large batch of SQL statements ,

// Microsoft SQL Server may stop processing the batch before all statements in the batch are executed.

// https://support.microsoft.com/en-us/kb/827575

// Uncomment the next line to flush all the pending result sets.



//while ( sqlsrv_next_result ( $stmt ) != NULL ){};



sqlsrv_free_stmt ( $stmt );

sqlsrv_close ( $conn );

?>

**Comment by meet-bhagdev** [comment] 2016-08-11 17:06
Awesome! I will go ahead and close the issue. Feel free to reopen it if needed.

**Closed** 2016-08-11 17:06 UTC
