### ISSUE TITLE
Retrieving results where there are prior selects that don't return result sets

### ISSUE THREAD

**Issue by LarnuUK** [Azure/msphpsql#130] opened 2016-08-10 15:58 UTC
I have having a problem with  sqlsrv_fetch_array when a query has other select statements in it prior. it seems that sqlsrv_fetch_array will always read the first select statement, even if it doesn't return a result set to the user. how do you get around this?

For example, the sp I have does the following:
`Select ltrim(rtrim(replace(replace(replace(Items,' ',''),';',''), char(10),''))) as Items
into #Emails
from WS.SplitEmails(@emails, CHAR(10))

Insert into WS.FileEmails_tbl (EmailAddress)
Select Items
from #Emails
where Items not in (Select sq.EmailAddress from WS.FileEmails_tbl sq)

Insert into WS.Files_tbl (FileName, FilePath, AddedByUser)
output inserted.FileID
Select  @FileName,
		@FilePath,
		(Select UserID from WS.Users_tbl U where U.Username = @AddedBy)

Drop table #Emails`

When I then use sqlsrv_fetch_array, it doesn't return any values, however, if i run the query in SSMS, I do. is this an intended "feature"? How do you get around it?

**Comment by meet-bhagdev** [comment] 2016-08-10 23:57
@LarnuUK This looks like expected behavior. Let me try to dig into it a little more.  

Your stored procedure contains 3 queries. The first 2 do not have any result set, and only the third one return the inserted FieleID.

When you first call sqlsrv_fetch_array, the result set cursor is still pointing to the first query, where there is no result set. To get your result set, you have to call sqlsrv_next_result() two times so that the result set cursor now points to the third query, then call sqlsrv_fetch_array.

To summarize, this might be a better way to go around this:

```
$stmt = sqlsrv_query(/* call your stored procedure here*/);

                                // at this point the result set cursor points to your first query
sqlsrv_next_result_set($stmt);  // now it points to the second query
sqlsrv_next_result_set($stmt);  // now it points to the third query, where we expect the FileID to return

print_r(sqlsrv_fetch_array($stmt));  // fetch array from the current result set cursor

// if you have other stored procedures and you don't want to count which row returns a result set, simply use a while loop on sqlsrv_next_result_set
/*
while (sqlsrv_next_result_set($stmt) != NULL) {
     print_r(sqlsrv_fetch_array($stmt));
}
*/
```
Let me know what your thoughts are on this recommendation?

**Comment by meet-bhagdev** [comment] 2016-08-25 00:17
@LarnuUK : Closing this based on our recommendation. Let me know if that works. If you have questions, we will re-open the issue.

**Closed by meet-bhagdev** 2016-08-25 00:17 UTC
