### ISSUE TITLE
Can't connect to SQL Server with PHP 7

### ISSUE THREAD

**Issue by klapsius** [Azure/msphpsql#107] opened 2016-07-06 12:24 UTC
I have problem with this string 

` $db = new PDO("sqlsrv:Server=SER-VER-NAME;Database=dbname", "login", "passw");`

and sometimes  error massage comes up: `Fatal error: Invalid handle returned ` 
 
Is it a bug?

**Comment by UncleHoo** [comment] 2016-07-06 15:42
I also am having the same issue.  I believe that it is a bug.  I am using PHP 7.0 along with PDO 4.0 on a x64 bit machine.

The same line of code works with PHP 5.4.12 and PDO 3.2.

**Comment by meet-bhagdev** [comment] 2016-07-06 18:23
Have you set up php.ini file correctly with the right name of dll? And if the dll is loaded (can you verify by using extension_loaded())?
Additionally, what version of the ODBC Driver are you using and is this on Linux or Windows?

**Comment by UncleHoo** [comment] 2016-07-06 18:29
Thanks for the quick reply.  I actually found the problem but haven't had time to post an update.  There is in fact no bug.  The problem is due to the fact that I was actually running version PDO 3.0 (not 3.2) which uses the "SQL Native Client" which I had installed on the server.  What I didn't have installed however was the ODBC Driver for SQL (neither 11 or 13).  After I installed the ODBC 13 driver for SQL it works fine.  However, when I checked the PHP / Server error logs, it never mentioned anything about missing drivers.  I don't know if this is something that you can add in a future release as it would make debugging much easier.  But the bottom line is that it now works -- you just have to make sure you have the correct SQL driver installed :)

But thanks again for the quick reply!

**Comment by meet-bhagdev** [comment] 2016-07-06 18:36
Awesome! Glad it worked out. Let us try to understand what went wrong with the error message as `Fatal error: Invalid handle returned `is not very informative. @klapsius Please follow @UncleHoo's recommendation. Closing the issue for now but happy to reopen if you still need assistance.

**Closed by meet-bhagdev** 2016-07-06 18:36 UTC

**Comment by klapsius** [comment] 2016-07-07 09:03
Sorry for late replay. I tried to validate everything. 

`$db = new PDO('sqlsrv:Server=SERVER;Database=DB', 'username', 'password');`

It works fine if login details correct or SQL is running. But if server is offline or i change login details (i need to validate anyway) then error message comes up: 
`Fatal error: Invalid handle returned`
If i change back to right data error message not disappears. It disappears after few minutes (5-10) or after i restart IIS server (i don't need restart machine only IIS

Details:
Windows Server 2012R2
IIS 8
PHP 7.0.7
Compiler MSVC14 (Visual C++ 2015) 
 ODBC 13
